### ISSUE TITLE
change phzABR to phzFFR in all relevant code

### ISSUE THREAD

**Issue by elladu** [gabenespoli/phzlab#11]
Since phzABR has been changed to phzFFR, this needs to be reflected in all code. noted in phz_combine, line 141:     TMP = phzABR_equalizeTrials(TMP, equalGrpVar, verbose);

change to phzFFR_equalizeTrials -- I haven't checked to see whether there are any other similar issues.

**Comment by gabenespoli** [comment]
I must have missed these when I changed from ABR to FFR (a0526a4b0f2ef09721957bb232c5acc4dc63944b). I've fixed this and some others i missed (ff7ca5954dd278d778668cb28d2f78a9b537b7a3).
